name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for Main App
      run: dotnet restore ./MonitoringApi/MonitoringApi.csproj

    - name: Restore dependencies for Unit Tests
      run: dotnet restore ./MonitoringApi.UnitTests/MonitoringApi.UnitTests.csproj

    - name: Restore dependencies for Integration Tests
      run: dotnet restore ./MonitoringApi.IntegrationTests/MonitoringApi.IntegrationTests.csproj

    - name: Build Main App
      run: dotnet build ./MonitoringApi/MonitoringApi.csproj --no-restore

    - name: Run Unit Tests
      run: dotnet test ./MonitoringApi.UnitTests/MonitoringApi.UnitTests.csproj --verbosity normal

    - name: Run Integration Tests
      run: dotnet test ./MonitoringApi.IntegrationTests/MonitoringApi.IntegrationTests.csproj --verbosity normal